version: '3'
services:
  web:
    build: ./frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    command: npm run start
  api:
    stdin_open: true
    tty: true
    build: ./kajabi-backend
    volumes:
      - ./kajabi-backend:/rails
    ports:
      - 5001:5001
